"""initial migration

Revision ID: 4c211a553f9d
Revises: 
Create Date: 2025-06-11 15:28:53.383432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c211a553f9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('block', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('transaction_action', sa.Text(), nullable=True),
    sa.Column('sponsored', sa.Boolean(), nullable=True),
    sa.Column('_from', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('transaction_fee', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('gas_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_block'), ['block'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_hash'), ['hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_block'))

    op.drop_table('transactions')
    # ### end Alembic commands ###
