"""add gas_data_fields

Revision ID: 6d022dd834f7
Revises: 4c211a553f9d
Create Date: 2025-06-11 15:59:59.023900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d022dd834f7'
down_revision: Union[str, None] = '4c211a553f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gas_used', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('cumulative_gas_used', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('input_data', sa.Text(), nullable=True))
        batch_op.drop_column('sponsored')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsored', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('input_data')
        batch_op.drop_column('cumulative_gas_used')
        batch_op.drop_column('gas_used')

    # ### end Alembic commands ###
